name: release-linux-x64

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |        
        sudo apt-get update && \
        sudo apt-get install -y \
        cmake \
        cmake-curses-gui \
        gdb \
        git \
        g++ \
        libbz2-dev \
        libcurl4-openssl-dev \
        libfreetype6-dev \
        libgeoip-dev \
        libglew-dev \
        libjpeg-dev \
        libmysqlclient-dev \
        libncursesw5-dev \
        libogg-dev \
        libopenal-dev \
        libsdl1.2-dev \
        libsdl2-dev \
        libtdb-dev \
        libvorbis-dev \
        mysql-client \
        ncurses-dev \
        opencl-dev \
        rsync \
        tmux \
        zip && \
        sudo apt-get clean
    - name: Compile
      run: |
        ./sp-tools.sh default_config
        ./sp-tools.sh init
        # following fails because of shallow clone on checkout
        #./sp-tools.sh install_default_paks 
        ./sp-tools.sh configure_cmake both
        ./sp-tools.sh build both
    - name: Dist package
      id: dist
      run: |
        source config.sh
        cd basepath/
        export DIST_FILE="${GAME_APP_NAME}-${GAME_APP_VERSION}-${GAME_APP_STAGE}.${{ github.workflow }}.zip"
        echo "::set-output name=dist-file::$(echo ${DIST_FILE})"
        zip -r "../${DIST_FILE}" .
        echo "::set-output name=game-app-name::$(echo $GAME_APP_NAME)"

    - name: Upload to Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: "./${{ steps.dist.outputs.dist-file }}"
        asset_name: "${{ steps.dist.outputs.dist-file }}"
        tag: ${{ github.ref }}
        overwrite: true
        body: "Automatically generated"

